#!/bin/bash
# synology-auto-mount installer for macOS.
#
# Mounts a Synology (or any) SMB share at /Volumes/<share> and installs a
# LaunchAgent that keeps it mounted: re-mounts after reboot, sleep/wake and
# network drops (checks every 60 seconds).
#
# Zero sudo. The password is saved to the login keychain by macOS itself
# (via one credentialed Finder-auth-stack mount) — it is never written to
# any file by this installer.
#
# Usage:
#   ./install.sh                        # fully interactive
#   ./install.sh HOST SHARE USER PASS   # non-interactive (agent-friendly)
set -euo pipefail

LABEL="dev.mahingbun.synology-automount"
SCRIPT_PATH="$HOME/.local/bin/synology-automount.sh"
PLIST_PATH="$HOME/Library/LaunchAgents/${LABEL}.plist"
LOG_PATH="$HOME/Library/Logs/synology-automount.log"

if [[ -t 1 ]]; then
    say()  { printf '\033[1;32m==>\033[0m %s\n' "$*"; }
    warn() { printf '\033[1;33mWARNING:\033[0m %s\n' "$*"; }
    die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }
else
    say()  { echo "==> $*"; }
    warn() { echo "WARNING: $*"; }
    die()  { echo "ERROR: $*" >&2; exit 1; }
fi

[[ "$(uname)" == "Darwin" ]] || die "This installer is macOS-only."

if [[ $# -ge 4 ]]; then
    NAS_HOST="$1"; NAS_SHARE="$2"; NAS_USER="$3"; NAS_PASS="$4"
else
    echo "Synology Auto Mount — keep an SMB share mounted on macOS."
    echo
    read -rp "NAS host or IP (e.g. 192.168.31.165): " NAS_HOST
    read -rp "Shared folder name (e.g. MacHardDrive): " NAS_SHARE
    read -rp "NAS username: " NAS_USER
    read -rsp "NAS password (input hidden): " NAS_PASS; echo
fi
[[ -n "${NAS_HOST// /}" ]] || die "host is required"
[[ -n "${NAS_SHARE// /}" ]] || die "share name is required"
[[ -n "${NAS_USER// /}" ]] || die "username is required"
[[ -n "${NAS_PASS// /}" ]] || die "password is required"
[[ "$NAS_PASS" != *'"'* && "$NAS_PASS" != *'\'* ]] \
    || die "password must not contain double quotes or backslashes"

MOUNT_POINT="/Volumes/${NAS_SHARE}"
DRY_RUN="${DRY_RUN:-0}"   # DRY_RUN=1 prints everything it would install, changes nothing

# ---- preflight ----------------------------------------------------------
say "Preflight: SMB port on ${NAS_HOST} ..."
nc -z -G 3 "$NAS_HOST" 445 >/dev/null 2>&1 \
    || die "Cannot reach ${NAS_HOST}:445. Check the IP and that SMB service is enabled in DSM."

if [[ "$DRY_RUN" == "1" ]]; then
    say "DRY RUN: no mounts, no LaunchAgent, no files will be written."
else
    # Stop any previous installation (idempotent re-install).
    launchctl bootout "gui/$(id -u)/${LABEL}" >/dev/null 2>&1 || true
fi

# ---- seed the keychain through macOS' own auth stack ---------------------
# A plain `security add-internet-password` entry is NOT readable by
# mount_smbfs on modern macOS (Apple partition check). One credentialed
# `mount volume` makes macOS store the entry itself, correctly.
if [[ "$DRY_RUN" == "1" ]]; then
    say "DRY RUN: would connect once with credentials to seed the keychain."
elif mount | grep -q " on ${MOUNT_POINT} (smbfs"; then
    say "${MOUNT_POINT} is already mounted."
else
    say "Connecting once with credentials (this saves the password into your login keychain) ..."
    osascript -e 'on run argv' \
              -e 'mount volume (item 1 of argv)' \
              -e 'end run' \
              "smb://${NAS_USER}:${NAS_PASS}@${NAS_HOST}/${NAS_SHARE}" >/dev/null \
        || die "First mount failed. Check username/password, or connect once manually in Finder (Cmd+K -> smb://${NAS_HOST}) and tick 'remember password'."
fi

# ---- prove the passwordless path works -----------------------------------
if [[ "$DRY_RUN" == "1" ]]; then
    say "DRY RUN: would unmount and remount passwordlessly to verify the keychain."
else
    say "Unmounting to verify the keychain-based remount ..."
    diskutil unmount "$MOUNT_POINT" >/dev/null 2>&1 \
        || diskutil unmount force "$MOUNT_POINT" >/dev/null 2>&1 || true
fi

# ---- generate the watchdog script ----------------------------------------
SCRIPT_OUT="$SCRIPT_PATH"
[[ "$DRY_RUN" == "1" ]] && SCRIPT_OUT="/dev/stdout"
[[ "$DRY_RUN" == "1" ]] || mkdir -p "$(dirname "$SCRIPT_PATH")"
cat > "$SCRIPT_OUT" <<SCRIPT
#!/bin/sh
# Generated by synology-auto-mount install.sh on $(date '+%Y-%m-%d').
# Keeps ${NAS_SHARE} mounted; runs at login and every 60s via launchd.
# Repo: https://github.com/mahingbun-dev/synology-auto-mount

NAS_HOST="${NAS_HOST}"
NAS_SHARE="${NAS_SHARE}"
NAS_USER="${NAS_USER}"
MOUNT_POINT="/Volumes/${NAS_SHARE}"
LOG="\$HOME/Library/Logs/synology-automount.log"

log() { echo "\$(date '+%Y-%m-%d %H:%M:%S') \$*" >> "\$LOG"; }

# Already mounted?
if mount | grep -q " on \${MOUNT_POINT} (smbfs"; then
    exit 0
fi

# Fast-fail when the NAS is unreachable: avoids Apple-event hangs and
# stray GUI password dialogs while off-network.
if ! nc -z -G 2 "\$NAS_HOST" 445 >/dev/null 2>&1; then
    log "skip: \${NAS_HOST}:445 unreachable"
    exit 0
fi

# Mount via the Finder auth stack: reads the password from the keychain
# (seeded during install) and creates /Volumes/<share> itself — no sudo.
log "mounting smb://\${NAS_USER}@\${NAS_HOST}/\${NAS_SHARE}"
if osascript -e 'on run argv' \\
             -e 'mount volume ("smb://" & (item 1 of argv) & "@" & (item 2 of argv) & "/" & (item 3 of argv))' \\
             -e 'end run' \\
             "\$NAS_USER" "\$NAS_HOST" "\$NAS_SHARE" >> "\$LOG" 2>&1; then
    log "mounted \${NAS_SHARE} -> \${MOUNT_POINT}"
    exit 0
else
    log "mount FAILED (details above)"
    exit 1
fi
SCRIPT
chmod +x "$SCRIPT_PATH" 2>/dev/null || true

if [[ "$DRY_RUN" == "1" ]]; then
    say "DRY RUN: would now test the script (passwordless remount), install"
    say "DRY RUN: the LaunchAgent at ${PLIST_PATH} and bootstrap it."
    say "DRY RUN complete — no changes were made."
    exit 0
fi

say "Testing the generated script (passwordless remount from keychain) ..."
"$SCRIPT_PATH" || die "Passwordless remount failed — see ${LOG_PATH}. Fix: in Finder press Cmd+K, connect smb://${NAS_HOST}, tick 'remember password', then re-run this installer."
mount | grep -q " on ${MOUNT_POINT} (smbfs" \
    || die "Script exited 0 but ${MOUNT_POINT} is not mounted. Check ${LOG_PATH}."

# ---- install the LaunchAgent ---------------------------------------------
mkdir -p "$(dirname "$PLIST_PATH")"
cat > "$PLIST_PATH" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${LABEL}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/sh</string>
        <string>${SCRIPT_PATH}</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>StartInterval</key>
    <integer>60</integer>
    <key>ProcessType</key>
    <string>Background</string>
    <key>StandardOutPath</key>
    <string>${LOG_PATH}</string>
    <key>StandardErrorPath</key>
    <string>${LOG_PATH}</string>
</dict>
</plist>
PLIST
plutil -lint "$PLIST_PATH" >/dev/null || die "Generated plist failed validation."

say "Loading LaunchAgent ${LABEL} ..."
launchctl bootstrap "gui/$(id -u)" "$PLIST_PATH" 2>/dev/null \
    || launchctl load "$PLIST_PATH" || die "Could not load the LaunchAgent."
sleep 2
launchctl kickstart "gui/$(id -u)/${LABEL}" 2>/dev/null || true

# ---- done ----------------------------------------------------------------
echo
say "Installed. ${NAS_SHARE} is mounted at ${MOUNT_POINT} and will"
say "re-attach automatically after reboot, sleep and network drops (<=60s)."echo
echo "  Watchdog script : ${SCRIPT_PATH}"
echo "  LaunchAgent     : ${PLIST_PATH}"
echo "  Log             : ${LOG_PATH}"
echo "  Pause/remount   : launchctl unload ${PLIST_PATH}   (load to resume)"
echo "  Uninstall       : ./uninstall.sh"
